#pragma once

#include <vector>
#include <string>

enum SCRIPT_TYPE
{
	BGSCROLLSCRIPT,
	CAMMOVESCRIPT,
	COOKIESKILLSCRIPT,
	DOUBLEJUMPSTATE,
	EFFECTSCRIPT,
	ENEMY,
	GAMEPLAYSPAWNSCRIPT,
	GAMEPLAYUISCRIPT,
	HITSTATE,
	HPBARSCRIPT,
	JELLYSCRIPT,
	JUMPBUTTONSCRIPT,
	JUMPSTATE,
	LANDSTATE,
	LINEAROBSTACLE,
	LYCHEESCRIPT,
	MISSILESCRIPT,
	MONSTERSCRIPT,
	MOVINGPLATFORMSCIRPT,
	OBSTRUCTSCRIPT,
	PARABOLICOBSTACLE,
	PENDULUMOBSTACLE,
	PLAYERSCRIPT,
	RUNSTATE,
	SCROLLSCRIPT,
	SLIDEBUTTONSCRIPT,
	SLIDESTATE,
	STATEMACHINE,
	STATICOBSTACLE,
	STATICPLATFORMSCRIPT,
	TIMEKEEPERSCRIPT,
	UIBUTTONSCRIPT,
	WORLDSCROLLSCRIPT,
};

using namespace std;

class CScript;

class ScriptMgr
{
public:
	static void GetScriptInfo(vector<wstring>& _vec);
	static CScript * GetScript(const wstring& _strScriptName);
	static CScript * GetScript(UINT _iScriptType);
	static const wchar_t * GetScriptName(CScript * _pScript);
};
